stages:
  #- build
  - docker
  - acceptance

# build:
#   stage: build
#   image: mcr.microsoft.com/dotnet/sdk:6.0
#   artifacts:
#     paths:
#       - CarPooling.API/bin/
#   script:
#     - cd CarPooling.API
#     - dotnet restore
#     - dotnet build --configuration Release

build_image:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  artifacts:
    paths:
      - Dockerfile
  script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build -f CarPooling.API/Dockerfile . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest


acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
